Update one.yml

diff --git a/.github/workflows/one.yml b/.github/workflows/one.yml
--- a/.github/workflows/one.yml
+++ b/.github/workflows/one.yml
@@ -7,8 +7,6 @@ on:
   # Triggers the workflow on push or pull request events but only for the "master" branch
   push:
     branches: [ "master" ]
-  pull_request:
-    branches: [ "master" ]
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
@@ -19,7 +17,7 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        stack: ['dotnet', 'java']
+        stack: ['dotnet', 'java', 'failing']
 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
@@ -28,3 +26,6 @@ jobs:
       # Runs a single command using the runners shell
       - name: Building stack for ${{ matrix.stack }}
         run: echo Hello, world!  ${{ matrix.stack }}
+      - name: Fail the job named 'failing'
+        if: ${{ matrix.stack }}== 'failing'
+        run: exit 1
